theme: minima
title: "伤心板子的博客"
author: olysad
description: "一个伤心的人，创作了一个博客，但他不希望别人和他一样伤心...."

include: 
  - _pages

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      permalink: /:categories/:title
